# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Motograms' do

end

target 'MotogramsTests' do

end

target 'MotogramsUITests' do

end

pod 'Google/SignIn'